name: 'See & Understand'
favicon: null
layout_spectrum: 0.40877
typography_spectrum: 0.22921
title: 'See & Understand'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e77638'
    - '#5b6690'
    - '#c72339'
    - '#8cacb5'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
